AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'MyApp

  Sample SAM Template for MyApp

  '
Globals:
  Function:
    Timeout: 3
Resources:
  HelloWorldFunction1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-test-6721/193e0bb8bb6308d7ce3e21e2ae85e4fd
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  HelloWorldFunction2:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloWorldFunction1
      - Arn
  HelloWorldFunctionIamRole2:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - HelloWorldFunction1Role
      - Arn
